### ISSUE TITLE
NoMethodError exceptions with image tagged 20230404_01

### ISSUE THREAD

**Issue by brycied00d** [yakumo-saki/docker-glitch-soc#7]
I've been running the `latest` tag for a little while now, pulling updates when available. With today's push of `latest` and `20230404_01`, Mastodon is raising `NoMethodError` exceptions in both the web and sidekiq workers.

If I roll back to the last-known working image tag `20230328_01`, everything runs correctly.

Just a guess, did a file get missed in packing, or perhaps an outdated/old copy of `has_user_settings.rb` was packed?

```
mastodon-web-1        | [cc363580-34ca-434e-8152-abb3208bce8b] method=GET path=/health format=html controller=HealthController action=show status=200 duration=2.34 view=2.02 db=0.00
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] method=GET path=/@mwl@io.mwl.io/110130021404215404 format=html controller=HomeController action=index status=500 error='NoMethodError: undefined method `[]' for nil:NilClass' duration=9.80 view=0.00 db=1.87
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae]   
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] NoMethodError (undefined method `[]' for nil:NilClass):
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae]   
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] app/models/concerns/has_user_settings.rb:63:in `setting_flavour'
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] app/controllers/concerns/theming_concern.rb:14:in `current_flavour'
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] app/controllers/concerns/theming_concern.rb:8:in `use_pack'
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] app/controllers/concerns/web_app_controller_concern.rb:25:in `set_pack'
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web-1        | [c9480d55-4953-42b5-bb0e-b5933ea386ae] lib/public_file_server_middleware.rb:18:in `call'
```

```
mastodon-sidekiq-1    | 2023-04-03T20:04:29.983Z pid=7 tid=2f2n class=FeedInsertWorker jid=00bbf4ca82fce3b9eaca477e elapsed=0.03 INFO: fail
mastodon-sidekiq-1    | 2023-04-03T20:04:29.983Z pid=7 tid=2f2n WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"FeedInsertWorker","args":[110136077034554785,109414876176916648,"home",{"update":null}],"jid":"00bbf4ca82fce3b9eaca477e","created_at":1680543167.700645,"enqueued_at":1680552269.9530928,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1680543167.7301023,"retry_count":8,"retried_at":1680548100.926524}}
mastodon-sidekiq-1    | 2023-04-03T20:04:29.983Z pid=7 tid=2f2n WARN: NoMethodError: undefined method `[]' for nil:NilClass
mastodon-sidekiq-1    | 2023-04-03T20:04:29.983Z pid=7 tid=2f2n WARN: /opt/mastodon/app/models/concerns/has_user_settings.rb:159:in `aggregates_reblogs?'
mastodon-sidekiq-1    | /opt/mastodon/app/lib/feed_manager.rb:63:in `push_to_home'
mastodon-sidekiq-1    | /opt/mastodon/app/workers/feed_insert_worker.rb:59:in `perform_push'
```

I have not attempted to build the images myself due to constraints on my own time, I'm sorry.

**Comment by yakumo-saki** [comment]
Thank you for using and writing issue.

I replace Dockerfile with official one.
And now new image with tag 20230406_0x is built. 
Please take a look.

**Comment by brycied00d** [comment]
I tried with `20230406_13` but same issue.

I tried with `ghcr.io/glitch-soc/mastodon:aa08a726545133a0af01fa51079724e9ae2134d5` and I'm getting the same errors. So this is an upstream issue with glitch-soc, or the issue is localized to my instance.

I will close this issue because it's not an issue with your build.

Thank you again. I'm sorry to have needlessly bothered you.

```
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] method=GET path=/home format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=385.12 view=0.00 db=218.84
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]   
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]      6: 
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]      7:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]      8: 
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]      9:   = render_initial_state
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]     10: 
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]     11: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]     12:   %noscript
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24]   
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/models/concerns/has_user_settings.rb:127:in `setting_hide_followers_count'
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/serializers/rest/account_serializer.rb:94:in `followers_count'
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/helpers/application_helper.rb:223:in `render_initial_state'
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/views/shared/_web_app.html.haml:9
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/views/shared/_web_app.html.haml:1
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/views/home/index.html.haml:7
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web-1        | [35917e60-f7a7-4248-bde6-2b64705d2b24] lib/public_file_server_middleware.rb:18:in `call'
```

```
mastodon-sidekiq-1    | 2023-04-06T23:44:44.704Z pid=7 tid=2hx7 class=FeedInsertWorker jid=26ce167c260b46bdfcab9f2c INFO: start
mastodon-sidekiq-1    | 2023-04-06T23:44:44.714Z pid=7 tid=2hpf class=DistributionWorker jid=b7601e49417d8054327daf5c elapsed=0.061 INFO: done
mastodon-sidekiq-1    | 2023-04-06T23:44:44.740Z pid=7 tid=2hx7 class=FeedInsertWorker jid=26ce167c260b46bdfcab9f2c elapsed=0.036 INFO: fail
mastodon-sidekiq-1    | 2023-04-06T23:44:44.740Z pid=7 tid=2hx7 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"FeedInsertWorker","args":[110154526531996079,109414876176916648,"home",{"update":null}],"jid":"26ce167c260b46bdfcab9f2c","created_at":1680824684.702636,"enqueued_at":1680824684.7027843}}
mastodon-sidekiq-1    | 2023-04-06T23:44:44.740Z pid=7 tid=2hx7 WARN: NoMethodError: undefined method `[]' for nil:NilClass
mastodon-sidekiq-1    | 2023-04-06T23:44:44.740Z pid=7 tid=2hx7 WARN: /opt/mastodon/app/models/concerns/has_user_settings.rb:159:in `aggregates_reblogs?'
mastodon-sidekiq-1    | /opt/mastodon/app/lib/feed_manager.rb:63:in `push_to_home'
mastodon-sidekiq-1    | /opt/mastodon/app/workers/feed_insert_worker.rb:59:in `perform_push'
mastodon-sidekiq-1    | 2023-04-06T23:44:45.698Z pid=7 tid=2hrn class=LinkCrawlWorker jid=8ebb679ce06ed4ea4d7c43e6 INFO: start
mastodon-sidekiq-1    | 2023-04-06T23:44:45.702Z pid=7 tid=2hrn class=LinkCrawlWorker jid=8ebb679ce06ed4ea4d7c43e6 elapsed=0.004 INFO: done
```

**Comment by brycied00d** [comment]
One final follow-up: The issue turned out to be my error. I had forgotten to run `rake db:migrate` after the update.

Apologies again for the frivolous issue.

**Comment by yakumo-saki** [comment]
Thank you for your follow up.
I'm glad the issue has been resolved.
